app = "cursorstack"
primary_region = "syd"
kill_signal = "SIGINT"
kill_timeout = 5
swap_size_mb = 512

# Non-sensitive environment variables
[env]
# IMPORTANT: Update this value here and in the health check section below
HEALTH_TOKEN = "ZW2mDXEHG5IJA46U1fwa4nvVjzXf0EXv"

[experimental]
allowed_public_ports = []
auto_rollback = true

[mounts]
source = "data"
destination = "/data"

[[services]]
internal_port = 8080
processes = ["app"]
protocol = "tcp"
script_checks = []

[services.concurrency]
hard_limit = 100
soft_limit = 80
type = "requests"

[[services.ports]]
handlers = ["http"]
port = 80
force_https = true

[[services.ports]]
handlers = ["tls", "http"]
port = 443

[[services.tcp_checks]]
grace_period = "1s"
interval = "15s"
restart_limit = 0
timeout = "2s"

[[services.http_checks]]
interval = "60s"
grace_period = "5s"
method = "get"
path = "/health"
protocol = "http"
timeout = "2s"
tls_skip_verify = false
headers = { X-Health-Token = "ZW2mDXEHG5IJA46U1fwa4nvVjzXf0EXv" }

[[services.http_checks]]
grace_period = "10s"
interval = "30s"
method = "GET"
timeout = "5s"
path = "/litefs/health"

# [[http_service.headers]]
#   for = "/*"
#   [http_service.headers.values]
#     # Prevents your web pages from being displayed in frames or iframes on other domains
#     X-Frame-Options = "SAMEORIGIN"
#     # Prevents browsers from interpreting files as a different MIME type
#     X-Content-Type-Options = "nosniff"
#     # Controls how much referrer information is shared when users navigate away from your site
#     Referrer-Policy = "strict-origin-when-cross-origin"
